# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sql-data-test:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  contactservice:
    ports:
      - 5001:5001
    environment:
      - ConnectionString=Server=sql-data-test;Database=ContactDb;User Id=sa;Password=Pass@word
