# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sql-data-test:
    image: mcr.microsoft.com/mssql/server:2019-latest

  contactservice:
    image: contactservice
    build:
      context: .
      dockerfile: ContactService/Dockerfile
    depends_on:
      - sql-data-test
